name: Pull Request Workflow
on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  laboratory_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Nx set shas
        uses: nrwl/nx-set-shas@76907e7e5d3cd17ddb5e2b123389f054bffcdd03 # v4

      - name: Install dependencies
        run: npm ci

      - name: Lint affected
        run: npx nx affected -t lint --parallel=3

      - name: Test affected
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build affected
        run: npx nx affected -t build --parallel=3

      - name: Build storybook affected
        run: npx nx affected -t build-storybook --parallel=3 --configuration=ci
